name: habit_tracker_mvp
description: A minimal, bright, modern habit tracker and task manager.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9
  uuid: ^4.0.0
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
